import Header from '@/components/headerPage/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from "./Provider"



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'pinterest.in',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* importing header for permanent place */}
        <Provider>
         <Header />
        {children}
        </Provider>
        </body>
    </html>
  )
}
